# Generated by Django 3.2 on 2023-01-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20230113_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentstatus',
            old_name='type',
            new_name='status',
        ),
    ]
